name: artemis_data_collector
channels:
  - conda-forge
dependencies:
  # -- Runtime dependencies
  # base: list all base dependencies here
  - python>=3.12  # please specify the minimum version of python here
  - versioningit
  # compute: list all compute dependencies here
  - psycopg>=3.2
  - requests
  - stomp.py
  # -- Development dependencies
  # utils:
  - pre-commit
  # package building:
  - python-build
  # test: list all test dependencies here
  - pytest
  - pytest-cov
