name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          use-mamba: true
          environment-file: environment.yml
          activate-environment: test
      - name: install
        run: |
          python -m pip install -e .
      - name: Stand up docker containers for ActiveMQ and PostgreSQL
        run: |
          docker compose up -d
          sleep 10
      - name: run unit tests
        run: |
          echo "running unit tests"
          python -m pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
      - name: Stand down docker containers for ActiveMQ and PostgreSQL
        run: |
          docker compose down
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5
        if:
          github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
